### ISSUE TITLE
Missing key fast_dev_run

### ISSUE THREAD

**Issue by AmbiakaTT** [IDEA-Research/detrex#254]
Traceback (most recent call last):
  File "tools/train_net.py", line 313, in <module>
    args=(args,),
  File "/home/ubuntu/detrex/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "tools/train_net.py", line 284, in main
    if cfg.train.fast_dev_run.enabled:
  File "/home/ubuntu/miniconda3/envs/detrex/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 354, in __getattr__
    key=key, value=None, cause=e, type_override=ConfigAttributeError
  File "/home/ubuntu/miniconda3/envs/detrex/lib/python3.7/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "/home/ubuntu/miniconda3/envs/detrex/lib/python3.7/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/ubuntu/miniconda3/envs/detrex/lib/python3.7/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/ubuntu/miniconda3/envs/detrex/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/ubuntu/miniconda3/envs/detrex/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/home/ubuntu/miniconda3/envs/detrex/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigAttributeError: Missing key fast_dev_run

I just ran train_net.py for the first time and got this error, Im pretty sure I registered the dataset and the model correctly, what could be the issue here?

**Comment by wangzhaoyang-508** [comment]
hello, I meet the same error, did you slove this?

**Comment by AmbiakaTT** [comment]
I already forgot how I fixed it, but you should add  fast_dev_run= dict({"enabled":False}) in your train.py file

**Comment by wangzhaoyang-508** [comment]
> I already forgot how I fixed it, but you should add fast_dev_run= dict({"enabled":False}) in your train.py file
 OK， thanks
