### ISSUE TITLE
 RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by heguyu** [IDEA-Research/detrex#259]
2 errors detected in the compilation of "E:/Py_Conda_Project/detrex/detrex/layers/csrc/DCNv3/dcnv3_cuda.cu".
    dcnv3_cuda.cu
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\torch\utils\cpp_extension.py", line 1814, in _run_ninja_build
        env=env)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
   
    The above exception was the direct cause of the following exception:
   
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "E:\Py_Conda_Project\detrex\setup.py", line 233, in <module>
        cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension.with_options(ninja=False)},
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
        return run_commands(dist)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
        dist.run_commands()
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\dist.py", line 1208, in run_command
        super().run_command(command)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\torch\utils\cpp_extension.py", line 765, in build_extensions
        build_ext.build_extensions(self)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions   
        self._build_extensions_serial()
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_s
erial
        self.build_extension(ext)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 556, in build_extension    
        depends=ext.depends,
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\torch\utils\cpp_extension.py", line 747, in win_wrap_ninja_compile
        with_cuda=with_cuda)
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\torch\utils\cpp_extension.py", line 1492, in _write_ninja_file_and_compile_ob
jects
        error_prefix='Error compiling objects for extension')
      File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]

运行 `pip install -e .`时候抛出的异常
以下是我的配置:
pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 
cuda: 11.6
我找了很多方法但并无用处，还望告知！

**Comment by rentainhe** [comment]
Do you have set the `CUDA_HOME` or install `ninja` during compiling? If not you can set `CUDA_HOME` as :

```bash
export CUDA_HOME=/path/to/cuda-11.3
```

or install ninja as:

```bash
pip install ninja
```

**Comment by lilong-epfl** [comment]
> 2 errors detected in the compilation of "E:/Py_Conda_Project/detrex/detrex/layers/csrc/DCNv3/dcnv3_cuda.cu". dcnv3_cuda.cu ninja: build stopped: subcommand failed. Traceback (most recent call last): File "C:\Users\admin01.conda\envs\detrex-main\lib\site-packages\torch\utils\cpp_extension.py", line 1814, in _run_ninja_build env=env) File "C:\Users\admin01.conda\envs\detrex-main\lib\subprocess.py", line 512, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> ```
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<string>", line 36, in <module>
>   File "<pip-setuptools-caller>", line 34, in <module>
>   File "E:\Py_Conda_Project\detrex\setup.py", line 233, in <module>
>     cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension.with_options(ninja=False)},
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\__init__.py", line 87, in setup
>     return distutils.core.setup(**attrs)
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
>     return run_commands(dist)
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
>     dist.run_commands()
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
>     self.run_command(cmd)
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>     super().run_command(command)
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\command\develop.py", line 34, in run
>     self.install_for_development()
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
>     self.run_command('build_ext')
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>     self.distribution.run_command(command)
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>     super().run_command(command)
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>     cmd_obj.run()
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
>     _build_ext.run(self)
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\torch\utils\cpp_extension.py", line 765, in build_extensions
>     build_ext.build_extensions(self)
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions   
>     self._build_extensions_serial()
>   File "C:\Users\admin01\.conda\envs\detrex-main\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_s
> ```
> 
> erial self.build_extension(ext) File "C:\Users\admin01.conda\envs\detrex-main\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension _build_ext.build_extension(self, ext) File "C:\Users\admin01.conda\envs\detrex-main\lib\site-packages\setuptools_distutils\command\build_ext.py", line 556, in build_extension depends=ext.depends, File "C:\Users\admin01.conda\envs\detrex-main\lib\site-packages\torch\utils\cpp_extension.py", line 747, in win_wrap_ninja_compile with_cuda=with_cuda) File "C:\Users\admin01.conda\envs\detrex-main\lib\site-packages\torch\utils\cpp_extension.py", line 1492, in _write_ninja_file_and_compile_ob jects error_prefix='Error compiling objects for extension') File "C:\Users\admin01.conda\envs\detrex-main\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error compiling objects for extension [end of output]
> 
> 运行 `pip install -e .`时候抛出的异常 以下是我的配置: pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 cuda: 11.6 我找了很多方法但并无用处，还望告知！

Hello， I meet the same problem, did you solve it?
